package com.flaminko.models;
// Generated Feb 28, 2023, 5:27:47 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CategoryId generated by hbm2java
 */
@Embeddable
public class CategoryId  implements java.io.Serializable {


     private int id;
     private int parentId;

    public CategoryId() {
    }

    public CategoryId(int id, int parentId) {
       this.id = id;
       this.parentId = parentId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="parent_id", nullable=false)
    public int getParentId() {
        return this.parentId;
    }
    
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoryId) ) return false;
		 CategoryId castOther = ( CategoryId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getParentId()==castOther.getParentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getParentId();
         return result;
   }   


}


