package com.flaminko.models;
// Generated Feb 28, 2023, 5:27:47 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ImagesId generated by hbm2java
 */
@Embeddable
public class ImagesId  implements java.io.Serializable {


     private int productCategoryId;
     private int productCategoryParentId;
     private int productId;

    public ImagesId() {
    }

    public ImagesId(int productCategoryId, int productCategoryParentId, int productId) {
       this.productCategoryId = productCategoryId;
       this.productCategoryParentId = productCategoryParentId;
       this.productId = productId;
    }
   


    @Column(name="product_category_id", nullable=false)
    public int getProductCategoryId() {
        return this.productCategoryId;
    }
    
    public void setProductCategoryId(int productCategoryId) {
        this.productCategoryId = productCategoryId;
    }


    @Column(name="product_category_parent_id", nullable=false)
    public int getProductCategoryParentId() {
        return this.productCategoryParentId;
    }
    
    public void setProductCategoryParentId(int productCategoryParentId) {
        this.productCategoryParentId = productCategoryParentId;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImagesId) ) return false;
		 ImagesId castOther = ( ImagesId ) other; 
         
		 return (this.getProductCategoryId()==castOther.getProductCategoryId())
 && (this.getProductCategoryParentId()==castOther.getProductCategoryParentId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductCategoryId();
         result = 37 * result + this.getProductCategoryParentId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


