package com.flaminko.models;
// Generated Feb 28, 2023, 5:27:47 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name="order_items"
    ,catalog="flamingoo"
)
public class OrderItems  implements java.io.Serializable {


     private OrderItemsId id;
     private OrderDetails orderDetails;
     private int quantity;
     private Set<Product> products = new HashSet<Product>(0);

    public OrderItems() {
    }

	
    public OrderItems(OrderDetails orderDetails, int quantity) {
        this.orderDetails = orderDetails;
        this.quantity = quantity;
    }
    public OrderItems(OrderDetails orderDetails, int quantity, Set<Product> products) {
       this.orderDetails = orderDetails;
       this.quantity = quantity;
       this.products = products;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderDetailsId", column=@Column(name="order_details_id", nullable=false) ), 
        @AttributeOverride(name="orderDetailsUserId", column=@Column(name="order_details_user_id", nullable=false) ) } )
    public OrderItemsId getId() {
        return this.id;
    }
    
    public void setId(OrderItemsId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public OrderDetails getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(OrderDetails orderDetails) {
        this.orderDetails = orderDetails;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="order_items_has_product", catalog="flamingoo", joinColumns = { 
        @JoinColumn(name="order_items_order_details_id", nullable=false, updatable=false), 
        @JoinColumn(name="order_items_order_details_user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_id", nullable=false, updatable=false), 
        @JoinColumn(name="product_category_parent_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


